### ISSUE TITLE
As STA Green Mobility I would like that the e-mobility web-component map explains me the meaning of the different colors used by the icons

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/webcomp-mobility-echarging-map#68]
Linked to [#63](https://github.com/noi-techpark/webcomp-mobility-echarging-dashboard/issues/63)

A concrete proposal would just be to have an additional section in the left panel

![Screenshot from 2023-04-14 06-26-33](https://user-images.githubusercontent.com/9825179/231941705-b3c47c19-2615-4ec3-8893-88cf63f91e9e.png)

**Comment by clezag** [comment]
@rcavaliere I thought a bit on how to do this without overloading the user with information and spending too much effort on it (e.g. creating a separate box with a complete legend, making it responsive on all devices etc.).

If I understood the problem correctly, the issue is primarily that the new teal color is not intuitive, whereas I feel that the other colors already communicate their meaning clearly and don't need further explanation.

If a user is not sure what a color means, they simply open the detail of a station and immediately understand what's going on because the plug icons are either green or red. At least this is how I felt when first interacting with it.

So my idea was to communicate the meaning of that specific color better once a detail box is opened.
I've changed the grey "info" icon next to the disclaimer to a teal one, I think this makes it much clearer that the color refers to the fact that there is no real time data available 
![image](https://user-images.githubusercontent.com/48801473/233575453-34f999ae-e55d-485c-b54e-3ecc834d8532.png)

I've put this change up in testing so you can play around with it.

Again, this was just an idea that was cheap and fast to do, let me know what you think.
Otherwise we can still do the legend, but I think it will be a bit more complicated than we initially thought, from a UX perspective.

**Comment by rcavaliere** [comment]
@clezag I like your proposal! In my view, we can deploy this improvement on production

**Comment by clezag** [comment]
@rcavaliere done
